In [26]:
import pandas as pd
import numpy as np
import os

In [27]:
script_dir = os.getcwd()
chicago_path = os.path.join(script_dir, '..', 'Data', 'Cleaned Datasets', 'Chicago_Inspections_Data', '11.7_Chicago_Food_Inspections_Cleaned_Reduced.csv')
newYork_path = os.path.join(script_dir, '..', 'Data', 'Cleaned Datasets', 'NYC_Inspections_Data', '11.16_NYC_Inspections_Cleaned_Reduced.csv')

chicago = pd.read_csv(chicago_path)
nyc = pd.read_csv(newYork_path)

In [28]:
chicago['Zip'] = chicago['Zip'].astype('Int64')
chicago['License #'] = chicago['License #'].astype('Int64')

chicago['DBA Name'] = chicago['DBA Name'].str.upper()

chicago = chicago[["License #", "DBA Name", "Risk", "Address", "City", "State", "Zip", "Inspection Date", "Facility Type", "Violations", "Results"]]

chicago.head()

,License #,DBA Name,Risk,Address,City,State,Zip,Inspection Date,Facility Type,Violations,Results
0,20470,MARQUETTE NATIONAL BANK,Risk 1 (High),6316 S WESTERN AVE,CHICAGO,IL,60636,2012-10-15T00:00:00Z,Restaurant,NaN,Out of Business
1,26281,HENRY O. TANNER ELEMENTARY,Risk 1 (High),7350 S Evans,CHICAGO,IL,60619,2012-05-15T00:00:00Z,School,"14. PREVIOUS SERIOUS VIOLATION CORRECTED, 7-42...",Fail
2,2314919,"CHICAGOLAND DELI INTERNATIONAL, INC",Risk 1 (High),3956 N NARRAGANSETT AVE,CHICAGO,IL,60634,2023-04-17T00:00:00Z,Grocery Store,"38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - ...",Pass
3,1649359,CORNER BAKERY CAFE,Risk 1 (High),360 N MICHIGAN AVE,CHICAGO,IL,60601,2012-09-17T00:00:00Z,Restaurant,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",Pass w/ Conditions
4,1491413,BURRITO BEACH # 8,Risk 1 (High),200 E OHIO ST,CHICAGO,IL,60611,2020-03-05T00:00:00Z,Restaurant,10. ADEQUATE HANDWASHING SINKS PROPERLY SUPPLI...,Pass

In [29]:
nyc["City"] = "NEW YORK CITY"
nyc["State"] = "NY"

nyc = nyc.rename(
    columns={"DBA": "DBA Name", "BORO": "Boro", "STREET": "Street", "ZIPCODE": "Zip", "CUISINE DESCRIPTION": "Cuisine Description", "INSPECTION DATE": "Inspection Date", "VIOLATION DESCRIPTION": "Violations", "CRITICAL FLAG": "Critical Flag"}
)

nyc = nyc[["CAMIS", "DBA Name", "Boro", "Critical Flag", "Street", "City", "State", "Zip", "Cuisine Description", "Inspection Date", "Violations"]]
nyc['Violations'] = nyc['Violations'].str.upper()

nyc.head()

,CAMIS,DBA Name,Boro,Critical Flag,Street,City,State,Zip,Cuisine Description,Inspection Date,Violations
0,50171238,SUSHI & SIPS CAFE @ STUDENT UNION BUILDING,Queens,Critical,56 AVENUE,NEW YORK CITY,NY,11364,Asian/Asian Fusion,2025-08-27T00:00:00Z,"FOOD CONTACT SURFACE NOT PROPERLY WASHED, RINS..."
1,40785023,SAHARA EAST,Manhattan,Critical,1 AVENUE,NEW YORK CITY,NY,10009,Middle Eastern,2023-10-03T00:00:00Z,"FOOD, SUPPLIES, OR EQUIPMENT NOT PROTECTED FRO..."
2,50136989,HOT SPOT GRILL & JERK,Bronx,Critical,WHITE PLAINS ROAD,NEW YORK CITY,NY,10470,Caribbean,2023-06-01T00:00:00Z,PROPERLY SCALED AND CALIBRATED THERMOMETER OR ...
3,50088048,TRIPLE DEUCE,Bronx,Critical,BOSTON ROAD,NEW YORK CITY,NY,10466,Caribbean,2025-10-16T00:00:00Z,FILTH FLIES OR FOOD/REFUSE/SEWAGE ASSOCIATED W...
4,50146361,CARAVAN UYGHUR CUISINE,Manhattan,Critical,BEAVER STREET,NEW YORK CITY,NY,10004,Asian/Asian Fusion,2025-10-02T00:00:00Z,FOOD PROTECTION CERTIFICATE (FPC) NOT HELD BY ...

## Optional: Save each cleaned reduced dataset

In [30]:
# chicago.to_csv(os.path.join(script_dir, '..', 'Data', 'Data Integration', '11.16_Chicago_Inspections_Reduced.csv'), index=False)
# nyc.to_csv(os.path.join(script_dir, '..', 'Data', 'Data Integration', '11.16_NYC_Inspections_Reduced.csv'), index=False)

In [31]:
final_df = pd.concat([nyc, chicago], ignore_index=True)
final_df.index = range(1, len(final_df) + 1)
final_df['RecordID'] = final_df.index

final_df = final_df[['RecordID', 'DBA Name', 'CAMIS', 'License #', 'Address', 'Street', 'City', 'Boro', 'State', 'Zip', 'Inspection Date', 'Risk', 'Critical Flag', 'Facility Type', 'Cuisine Description', 'Violations', 'Results']]
final_df['CAMIS'] = final_df['CAMIS'].astype('Int64')
final_df

,RecordID,DBA Name,CAMIS,License #,Address,Street,City,Boro,State,Zip,Inspection Date,Risk,Critical Flag,Facility Type,Cuisine Description,Violations,Results
1,1,SUSHI & SIPS CAFE @ STUDENT UNION BUILDING,50171238,<NA>,NaN,56 AVENUE,NEW YORK CITY,Queens,NY,11364,2025-08-27T00:00:00Z,NaN,Critical,NaN,Asian/Asian Fusion,"FOOD CONTACT SURFACE NOT PROPERLY WASHED, RINS...",NaN
2,2,SAHARA EAST,40785023,<NA>,NaN,1 AVENUE,NEW YORK CITY,Manhattan,NY,10009,2023-10-03T00:00:00Z,NaN,Critical,NaN,Middle Eastern,"FOOD, SUPPLIES, OR EQUIPMENT NOT PROTECTED FRO...",NaN
3,3,HOT SPOT GRILL & JERK,50136989,<NA>,NaN,WHITE PLAINS ROAD,NEW YORK CITY,Bronx,NY,10470,2023-06-01T00:00:00Z,NaN,Critical,NaN,Caribbean,PROPERLY SCALED AND CALIBRATED THERMOMETER OR ...,NaN
4,4,TRIPLE DEUCE,50088048,<NA>,NaN,BOSTON ROAD,NEW YORK CITY,Bronx,NY,10466,2025-10-16T00:00:00Z,NaN,Critical,NaN,Caribbean,FILTH FLIES OR FOOD/REFUSE/SEWAGE ASSOCIATED W...,NaN
5,5,CARAVAN UYGHUR CUISINE,50146361,<NA>,NaN,BEAVER STREET,NEW YORK CITY,Manhattan,NY,10004,2025-10-02T00:00:00Z,NaN,Critical,NaN,Asian/Asian Fusion,FOOD PROTECTION CERTIFICATE (FPC) NOT HELD BY ...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223225,223225,MARGIES CANDIES,<NA>,1622713,1813 W MONTROSE AVE,NaN,CHICAGO,NaN,IL,60613,2013-10-22T00:00:00Z,Risk 1 (High),NaN,Restaurant,NaN,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",Fail
223226,223226,THE GRILLING CATERING AND DELIVERY COMPANY,<NA>,2120233,302 E 75TH ST,NaN,CHICAGO,NaN,IL,60619,2011-09-27T00:00:00Z,Risk 1 (High),NaN,Catering,NaN,NaN,Fail
223227,223227,POCKETS HYDE PARK,<NA>,2153361,1309 E 53RD ST,NaN,CHICAGO,NaN,IL,60615,2013-10-09T00:00:00Z,Risk 2 (Medium),NaN,Restaurant,NaN,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",Pass
223228,223228,THE PLAY ROOM,<NA>,1697530,7958 W BELMONT AVE,NaN,CHICAGO,NaN,IL,60634,2014-07-16T00:00:00Z,Risk 1 (High),NaN,Restaurant,NaN,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,Pass
223229,223229,MIKOS,<NA>,1045159,3000 W LYNDALE ST,NaN,CHICAGO,NaN,IL,60647,2014-09-10T00:00:00Z,Risk 2 (Medium),NaN,Restaurant,NaN,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",Pass

## Optional: Save to CSV

In [32]:
# final_df.to_csv(os.path.join(script_dir, '..', 'Data', 'Data Integration', '11.16_Inspections.csv'), index=False)

___

In [33]:
# Reducing for Github Repo
final_red = final_df.sample(frac = .75, random_state=477)
final_red

,RecordID,DBA Name,CAMIS,License #,Address,Street,City,Boro,State,Zip,Inspection Date,Risk,Critical Flag,Facility Type,Cuisine Description,Violations,Results
174415,174415,THEATER WIT NFP,<NA>,2037878,1229 W BELMONT AVE,NaN,CHICAGO,NaN,IL,60657,2010-07-01T00:00:00Z,Risk 3 (Low),NaN,Restaurant,NaN,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,Fail
182294,182294,"WEST TOWN DAYCARE ,LLC",<NA>,2570038,2751 W CORTEZ ST,NaN,CHICAGO,NaN,IL,60622,2019-07-25T00:00:00Z,Risk 1 (High),NaN,1023 CHILDERN'S SERVICES FACILITY,NaN,NaN,Pass
171418,171418,CHILDREN'S HOME AND AID SOCIETY OF ILLINOIS,<NA>,2215528,1701 W 63RD ST,NaN,CHICAGO,NaN,IL,60636,2023-04-21T00:00:00Z,Risk 1 (High),NaN,Daycare Above and Under 2 Years,NaN,NaN,No Entry
73133,73133,MCLOUGHLIN'S,40587835,<NA>,NaN,BROADWAY,NEW YORK CITY,Queens,NY,11106,2024-05-23T00:00:00Z,NaN,Critical,NaN,Irish,"FOOD CONTACT SURFACE NOT PROPERLY WASHED, RINS...",NaN
21130,21130,REX,50125902,<NA>,NaN,10 AVENUE,NEW YORK CITY,Manhattan,NY,10019,2024-11-21T00:00:00Z,NaN,Critical,NaN,Coffee/Tea,EVIDENCE OF RATS OR LIVE RATS IN ESTABLISHMENT...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132983,132983,TAQUERIA Y FONDA LA MEXICANA,41486399,<NA>,NaN,AMSTERDAM AVENUE,NEW YORK CITY,Manhattan,NY,10025,2023-02-08T00:00:00Z,NaN,Not Critical,NaN,Mexican,NON-FOOD CONTACT SURFACE OR EQUIPMENT MADE OF ...,NaN
5143,5143,WING HING RESTAURANT,50123658,<NA>,NaN,ROGERS AVENUE,NEW YORK CITY,Brooklyn,NY,11225,2023-04-06T00:00:00Z,NaN,Critical,NaN,Chinese,COLD TCS FOOD ITEM HELD ABOVE 41 °F; SMOKED OR...,NaN
174317,174317,SMART LEARNING CENTER LLC,<NA>,2231589,2839-2841 S ARCHER AVE,NaN,CHICAGO,NaN,IL,60608,2025-04-18T00:00:00Z,Risk 2 (Medium),NaN,after school program,NaN,NaN,Pass
24208,24208,TACOMBI,50072348,<NA>,NaN,5 AVENUE,NEW YORK CITY,Manhattan,NY,10118,2025-04-23T00:00:00Z,NaN,Not Critical,NaN,Tex-Mex,THAWING PROCEDURE IMPROPER.,NaN
1206,1206,CARVEL 2848,40959012,<NA>,NaN,86 STREET,NEW YORK CITY,Brooklyn,NY,11214,2023-09-20T00:00:00Z,NaN,Critical,NaN,Frozen Desserts,NO HAND WASHING FACILITY IN OR ADJACENT TO TOI...,NaN

## Optional: Save Reduced file to CSV

In [34]:
# final_red.to_csv(os.path.join(script_dir, '..', 'Data', 'Data Integration', '11.16_Inspections_Reduced.csv'), index=False)